[phases.setup]
nixPkgs = [
  "php84.withExtensions (exts: with exts; [ intl zip pdo pdo_pgsql mbstring bcmath openssl ])",
  "php84Packages.composer"
]

[phases.build]
cmds = [
  "php -m",
  "composer install --optimize-autoloader --no-interaction"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
